### PR TITLE
Add file extension for log

### LINKED ISSUE #2477: core log filename should be compatible with github
### What version of Music Assistant has the issue?

2.0.6

### What version of the Home Assistant Integration have you got installed?

2024.6.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When downloading the log file, the default name is just "log" without an extension. The issue filing instructions say to drag and drop the file, but it is not possible without renaming it to a supported extension, such as .txt . 

### How to reproduce

1. go to MA / settings / core
2. click "download logfile" at the bottom
3. open an issue on MA / HASS
4. drag and drop the file to one of the text boxes, or use the attach button
5. get the following error

image

### Music Providers

N/A

### Player Providers

N/A

### Full log output

N/A

### Additional information

I would suggest .txt for small logs . For anything over the 25MB default github file limit (or 100MB for paid github plan), use some supported compressed format.

Obviously, this is not the most pressing issue, but anything that shortens the issue filing time is a win in my book. I would submit a PR myself if I knew where to look.

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

### PR DESCRIPTION
**Pull request by MelHarbour**
Fixes https://github.com/music-assistant/hass-music-assistant/issues/2477

Adding a file extension to the log.

### CODE REVIEW

**Review by marcelveldt — APPROVED** [review]
note that this will also require a server change.
another approach would be to fetch it here and then offer it to the client

**Comment by MelHarbour** [comment]
Happy to go with 'architects verdict' here - clearly either approach would work fine. Let me know either way and I'll make the changes.

**Comment by marcelveldt** [comment]
> Happy to go with 'architects verdict' here - clearly either approach would work fine. Let me know either way and I'll make the changes.

I have no preference, do you ?
Adjusting the server is also not a lot of work so I make it your choice :-)

**Comment by OzGav** [comment]
@MelHarbour Just following up on this one?

**Comment by MelHarbour** [comment]
Haven't had time to sit down and do the server changes yet. Possibly tomorrow.

**Comment by MelHarbour** [comment]
@marcelveldt thinking about it, I suspect the 'proper' way to do it would be to control non-API access through the front end, so it would serve the 'file' itself. However in the interests of keeping things moving forwards at the moment, I'll just patch the server for the time being.

**Review by marcelveldt — APPROVED** [review]
Thanks!

**Pull request merged**
