### PR TITLE
Update Polish translations

### PR DESCRIPTION
**Pull request by LukaszP2**

### CODE REVIEW

**Comment by marcelveldt** [comment]
Thanks for the translations update, however we switched to Lokalize as platform for translations, which is even easier to submit updates.

@jozefKruszynski can you add Lukasz to the Polish translations ?

**Review by marcelveldt — APPROVED** [review]

**Comment by marcelveldt** [comment]
Thanks @LukaszP2 !

@jozefKruszynski could you add Lukasz to the Lokalize platform for next time ?

**Comment by jozefKruszynski** [comment]
Will do, honestly not sure how I missed the original request for this.

**Comment by jozefKruszynski** [comment]
@LukaszP2 You can add yourself from the following link please.

https://app.lokalise.com/public/321419046440c0f2bba414.05634832/

You should be able to choose Polish from the dropdown as the language you would like to contribute, as seen in the discussion post here:
https://github.com/orgs/music-assistant/discussions/1216

**Pull request merged**
