### PR TITLE
Lokalise-cron-download

### PR DESCRIPTION
**Pull request by jozefKruszynski**
This should download the translations every Monday at 2:00 am

### CODE REVIEW

**Review by OzGav — DISMISSED** [review]
Fingers crossed

**Comment by jozefKruszynski** [comment]
I tested the download bit on my machine and it works as expected, the merge request bit of the workflow might need some tweaking

**Comment by OzGav** [comment]
I was just looking to see where it says to download all languages. That may be a default?

**Comment by jozefKruszynski** [comment]
It is

**Comment by OzGav** [comment]
I didn't change the others here but just in case this is important these other options are set

image

image

I see these options also in the API

**Comment by jozefKruszynski** [comment]
Added those options

**Comment by OzGav** [comment]
I know you said you tested this but I see some options have a = and some don't? Is that correct?

**Review by OzGav — DISMISSED** [review]
Lets see what happens!

**Review by OzGav — APPROVED** [review]
Looks good.

**Comment by jozefKruszynski** [comment]
> I know you said you tested this but I see some options have a = and some don't? Is that correct?

Supposedly booleans require = and strings don't.

**Pull request merged**
