### PR TITLE
Reduce loading jank on home screen

### PR DESCRIPTION
**Pull request by JeffersonBledsoe**
Right now, we're displaying rows and items as the data is ready. This PR adds a Suspense wrapper around the loading to wait until all of the rows are ready before we display the page, reducing the layout shifting and flickering as the data is loading in.

### Todo

- [x] Nicer loading UI - I went with the spinner. I couldn't easily get it to fill the page so it displays at the start of the page for now
  - Spotify has a nice Skeleton UI, we should try to do something similar in the future?
    - Spotify loading skeleton UI
- [x] Ensure that 'Currently playing' is also waited on
- [x] The thumbnail in the 'now playing' doesn't display the artwork
- [x] The thumbnail for "currently playing" items is invisible and the wrong size
- [ ] Fix 'Browse' thumbnail on the homepage displaying an icon and the fallback
- [ ] Playlist thumbnail shows a broken image rather than the 'avatar' fallback

## Before

https://github.com/music-assistant/frontend/assets/30210785/270c2ee7-b85e-42f7-ab32-749ba6bad6b5

## After

https://github.com/music-assistant/frontend/assets/30210785/2f4f3aa6-dce7-4fe7-9c70-405ddff95d33

### CODE REVIEW

**Comment by marcelveldt** [comment]
Nice that you started working on this! It has been on my todo list for a long time to make this smoother, especially the image loading that looks really weird now.

**Comment by JeffersonBledsoe** [comment]
> especially the image loading that looks really weird now.

Is this with regards to how it starts empty, then shows the loading spinner then shows the album art and how it does this for each album? Happy to hear how you think it should behave and I'll try to work it in!

**Comment by marcelveldt** [comment]
> > especially the image loading that looks really weird now.
> 
> Is this with regards to how it starts empty, then shows the loading spinner then shows the album art and how it does this for each album? Happy to hear how you think it should behave and I'll try to work it in!

Well, yeah, it should somehow have a placeholder or calculated reserved space.

**Comment by JeffersonBledsoe** [comment]
@marcelveldt Would you mind giving the image loading a test using the latest commit? I'm still working on some things and want to make sure I haven't missed anything obvious (for example, somewhere the `MediaItemThumb` component is used at a custom dimension and so it doesn't render right). I still need to restore using the calculated fallback image based on the media type being displayed (the code at the minute always uses the 'album' fallback image).

I've resolved the image placeholder size issue, `v-img` seems to do it's own version of lazy-loading ontop of the card being lazy-loaded, causing this chain of lazy loading which is why you get the jump. I've switched to a normal `` element with native HTML lazy loading on it (it's supported in all the browsers we support according to the browserslist) and am using a CSS background image as the fallback. Quick video below to demonstrate how it behaves using the latest commit.


https://github.com/music-assistant/frontend/assets/30210785/2f4f3aa6-dce7-4fe7-9c70-405ddff95d33

**Comment by marcelveldt** [comment]
this one ready for review now ?

**Comment by JeffersonBledsoe** [comment]
> this one ready for review now ?

Yep, ready for review now!

**Review by marcelveldt — APPROVED** [review]
Looks good!
Thanks!

**Pull request merged**
